ALTER TABLE "Groups_in_queue" DROP CONSTRAINT IF EXISTS "Groups_in_queue_fk2";
ALTER TABLE "Groups_in_queue" DROP CONSTRAINT IF EXISTS "Groups_in_queue_fk1";
ALTER TABLE "Queues" DROP CONSTRAINT IF EXISTS "Queues_fk3";
ALTER TABLE "Queues" DROP CONSTRAINT IF EXISTS "Queues_fk2";
ALTER TABLE "Groups" DROP CONSTRAINT IF EXISTS "Groups_fk3";
ALTER TABLE "Departments" DROP CONSTRAINT IF EXISTS "Departments_fk3";
ALTER TABLE "Users" DROP CONSTRAINT IF EXISTS "Users_fk4";

DROP TABLE IF EXISTS "Groups_in_queue";
DROP TABLE IF EXISTS "Queues";
DROP TABLE IF EXISTS "Available";
DROP TABLE IF EXISTS "Users";
DROP TABLE IF EXISTS "Groups";
DROP TABLE IF EXISTS "Departments";
DROP TABLE IF EXISTS "Faculties";
